name: Build, Release and Stage

on:
  push:
    branches:
      - main
      - next

# Cancel in-progress jobs or runs for the current workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: wonderflow-bv/wanda/.github/workflows/ci-workflow.yml@main
    secrets:
      WF_TOKEN: ${{ secrets.WONDERFLOW_WORKFLOW_TOKEN }}
      NPM_TOKEN: ${{ secrets.WONDERFLOW_NPM_TOKEN }}
    with:
      release: true
